name: lint check

on: push

jobs:
  check lint:
  runs-on: ubuntu-latest

  steps:
    - name : checkout code
    - usese: actions/checkout@v4

    - name: say hello
    - run: echo "Hello workflows"
